### ISSUE TITLE
issue when getting in the passenger set.

### ISSUE THREAD

**Issue by AamiRobin** [emtneutrino/races#5]
Hello there, 
I found an issue with this script after a recent update. when someone is on the driving set if other players try to get into cars they teleport into the car there is no animation for getting into the car. I can send a video if you want to see guys. also if possible add an option to make the marker bigger. thanks, I love this script.

**Comment by emtneutrino** [comment]
I haven't found a way to make the animation of getting into the passenger seats play.  I only know how to teleport the player into the passenger seats.

If you're talking about increasing/decreasing the radius of a waypoint, from the README.md:
You can increase or decrease the radius of an existing waypoint in the world, but not in the waypoint map.  There are minimum and maximum radius limits to waypoints.  To increase the radius of the waypoint, select the waypoint in the world, then press 'Up Arrow' on a keyboard or up DPAD.  To decrease the radius of the waypoint, select the waypoint in the world, then press 'Down Arrow' on a keyboard or down DPAD.

If you're talking about making the size of the marker at a waypoint increase, it should increase in size when you increase the radius.  If you don't want to increase the radius, I'll consider making it bigger if other people want the same thing.

**Comment by emtneutrino** [comment]
I figured out how to play seating animations when entering a vehicle.  Latest version has been updated.
